name: Check Secrets
on:
  workflow_call:
    inputs:
      stub:
        required: false
        type: string
        default: "stub"
jobs:
  test-secrets-accessable:
    name: Test secrets accessable
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: ${{ secrets.S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.S3_DEPLOY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_DEPLOY_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.S3_REGION }}
    steps:
      # Check whether 
      - name: Test secrets accessable
        run: echo BUCKET_NAME | sed -e 's/\(.\)/\1 /g'
      - name: Check deploy secrets
        run: if [ -z ${AWS_ACCESS_KEY_ID+x} ]; then echo "access key is unset"; else echo "access key is set"; fi
      - name: Check deploy secrets
        run: if [ -z ${AWS_SECRET_ACCESS_KEY+x} ]; then echo "secret key is unset"; else echo "secret key is set"; fi
      - name: Check deploy secrets
        run: if [ -z ${AWS_DEFAULT_REGION+x} ]; then echo "region is unset"; else echo "region is set"; fi
  