#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  test-secrets-accessable:
    name: Test secrets accessable
    uses: ./.github/workflows/_check_secrets.yml
    secrets:
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      S3_DEPLOY_ID: ${{ secrets.S3_DEPLOY_ID }}
      S3_DEPLOY_KEY: ${{ secrets.S3_DEPLOY_KEY }}
      S3_REGION: ${{ secrets.S3_REGION }}
    
    

  duckdb-stable-build:
    name: Build extension binaries (DuckDB v0.10.2)
    needs: test-secrets-accessable
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v0.10.2
    with:
      duckdb_version: v0.10.2
      extension_name: sheetreader
      exclude_archs: "windows_amd64_rtools"

  duckdb-stable-deploy:
    name: Deploy extension binaries (DuckDB v0.10.2)
    needs: duckdb-stable-build
    uses: ./.github/workflows/_extension_deploy.yml
    secrets: inherit
    with:
      duckdb_version: v0.10.2
      extension_name: sheetreader
      deploy_latest: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}
      exclude_archs: "windows_amd64_rtools"
